# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

- name:     This playbook will configure the cni network plugin to be calico
  hosts:    control_planes
  run_once: true

  vars_files:
    - vars/default-settings.yaml
    - group_vars/kvm_guest/cloud_images.yaml
    - group_vars/kvm_guest/cni_plugins.yaml
    
  tasks:

    - block:
        - name: Loading CentOS 7 cluster samples
          include_vars:
            file:        vars/testlab_samples/centos-7.yaml
            name:        c7x
        - name: Loading CentOS 8 Stream cluster samples
          include_vars:
            file:        vars/testlab_samples/centos-8-stream.yaml
            name:        c8s
        - name: Loading Ubuntu 20.04 cluster samples
          include_vars:
            file:        vars/testlab_samples/ubuntu-20.04.yaml
            name:        u2004
        - name: Loading Ubuntu 20.10 cluster samples
          include_vars:
            file:        vars/testlab_samples/ubuntu-20.10.yaml
            name:        u2010
        - name: Loading Your custom cluster definition
          include_vars:
            file:        vars/clusters.yaml
            name:        custo
        - name: Merging all cluster definitions
          set_fact:
            clusters: "{{ custo | combine(c7x, recursive=True) | combine(c8s, recursive=True) | combine(u2004, recursive=True) | combine(u2010, recursive=True) }}"

    - name:  Kube setup calico network plugin -- Current provisioning facts of the VMs 
      debug:
        var: ansible_local['homelab-kubernetes-provider']

    - name:  Kube setup calico network plugin -- Configure the first control plane
      block:

        - name:       Kube setup calico network plugin -- Downloading calico plugin definition
          get_url:    
            url:      "{{ cni_plugins.calico.k8s_definition_url }}"
            dest:     /tmp/calico_cni_plugin.yaml

        - name:       Kube setup calico network plugin -- Asking to kubernetes to apply the calico cni plugins
          command:    kubectl apply -f /tmp/calico_cni_plugin.yaml

        - name:       Kube setup calico network plugin  -- Waiting until calico pod has been created
          shell:      "kubectl get pods --namespace=kube-system --selector k8s-app=calico-node --output=jsonpath='{.items[*].metadata.name}'"
          register:   pods_creation_checking
          until:      item in pods_creation_checking.stdout
          delay:      10
          with_items:
            - "calico-node"
          retries:    30

        - name:       Kube setup calico network plugin -- Waiting until calico pods readiness
          shell:      "kubectl wait pods --namespace=kube-system --selector k8s-app=calico-node --for=condition=Ready --timeout=600s"
          register:   pods_readiness_checking

        - name:       Kube setup calico network plugin  -- Waiting until kube-dns pod has been created
          shell:      "kubectl get pods --namespace=kube-system --selector k8s-app=kube-dns --output=jsonpath='{.items[*].metadata.name}'"
          register:   pods_creation_checking
          until:      item in pods_creation_checking.stdout
          delay:      10
          with_items:
            - "coredns"
          retries:    30

        - name:       Kube setup calico network plugin -- Waiting until kube-dns pods readiness
          shell:      "kubectl wait pods --namespace=kube-system --selector k8s-app=kube-dns --for=condition=Ready --timeout=600s"
          register:   pods_readiness_checking


        - name: Kube setup calico network plugin -- Storing new state inside the homelab-kubernetes-provider custom fact
          lineinfile:
            path:   /etc/ansible/facts.d/homelab-kubernetes-provider.fact
            line:   kube_network_plugin=calico
          become:   true
  
        - name: Kube setup calico network plugin -- Reload the homelab-kubernetes-provider custom fact
          setup:
            filter: ansible_local          

      when: 
        - inventory_hostname == groups['control_planes'][0]
        - clusters.definition[cluster_name].cni_plugin == 'calico'
        - ansible_local['homelab-kubernetes-provider']['setup']['kube_network_plugin'] is not defined
