# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

- name:     This playbook will configure the ingress to be nginx
  hosts:    control_planes
  run_once: true

  vars_files:
    - vars/default-settings.yaml
    - group_vars/kvm_guest/cloud_images.yaml
    - group_vars/kvm_guest/ingress.yaml
    
  tasks:

    - block:
        - name: Loading CentOS 7 cluster samples
          include_vars:
            file:        vars/testlab_samples/centos-7.yaml
            name:        c7x
        - name: Loading CentOS 8 Stream cluster samples
          include_vars:
            file:        vars/testlab_samples/centos-8-stream.yaml
            name:        c8s
        - name: Loading Ubuntu 20.04 cluster samples
          include_vars:
            file:        vars/testlab_samples/ubuntu-20.04.yaml
            name:        u2004
        - name: Loading Ubuntu 20.10 cluster samples
          include_vars:
            file:        vars/testlab_samples/ubuntu-20.10.yaml
            name:        u2010
        - name: Loading Your custom cluster definition
          include_vars:
            file:        vars/clusters.yaml
            name:        custo
        - name: Merging all cluster definitions
          set_fact:
            clusters: "{{ custo | combine(c7x, recursive=True) | combine(c8s, recursive=True) | combine(u2004, recursive=True) | combine(u2010, recursive=True) }}"

    - name:  Kube setup nginx ingress -- Current provisioning facts of the VMs 
      debug:
        var: ansible_local['homelab-kubernetes-provider']

    - name:  Kube setup nginx ingress -- Computing instance directory
      set_fact:
        instance_dir: "instances/{{ lookup('file', '/var/lib/dbus/machine-id') }}"
        
    - name:  Kube setup nginx ingress -- Configure the first control plane
      block:

        - name:       Kube setup nginx ingress -- Downloading nginx ingress definition
          get_url:    
            url:      "{{ ingress.nginx.k8s_definition_url }}"
            dest:     /tmp/nginx_ingress.yaml

        - name:       Kube setup nginx ingress -- Asking to kubernetes to apply the nginx ingress
          command:    kubectl apply -f /tmp/nginx_ingress.yaml

        - name:       Kube setup nginx ingress  -- Waiting until ingress pod has been created
          shell:      "kubectl get pods --namespace=ingress-nginx --output=jsonpath='{.items[*].metadata.name}'"
          register:   pods_creation_checking
          until:      item in pods_creation_checking.stdout
          delay:      10
          with_items:
            - "ingress-nginx-admission-create"
            - "ingress-nginx-admission-patch"
            - "ingress-nginx-controller"
          retries:    30

        - name:       Kube setup nginx ingress -- Waiting until ingress pods readiness
          shell:      "kubectl wait --namespace=ingress-nginx --for=condition=Ready pods --selector app.kubernetes.io/component=controller  --timeout=600s"
          register:   pods_readiness_checking

        - name:       Kube setup nginx ingress -- Retreiving ingress port
          shell:      kubectl get svc ingress-nginx-controller  -n ingress-nginx -o jsonpath='{..spec.ports[?(@.name=="{{ item }}")].nodePort}'
          loop:
            - http
            - https
          register:   ports

        - name: Kube setup nginx ingress -- Storing the http ingress port
          copy:
            dest:      "{{ instance_dir }}/{{ cluster_name }}/kubelet/ingress_http_port.txt"
            content:   "{{ ports.results[0].stdout }}"
          delegate_to: localhost
          vars:
            ansible_python_interpreter: /usr/bin/python3

        - name: Kube setup nginx ingress -- Storing the https ingress port
          copy:
            dest:      "{{ instance_dir }}/{{ cluster_name }}/kubelet/ingress_https_port.txt"
            content:   "{{ ports.results[1].stdout }}"
          delegate_to: localhost
          vars:
            ansible_python_interpreter: /usr/bin/python3

        - name:       Kube setup nginx ingress -- Storing new state inside the homelab-kubernetes-provider custom fact
          lineinfile:
            path:     /etc/ansible/facts.d/homelab-kubernetes-provider.fact
            line:     kube_ingress=nginx
          become:     true
  
        - name:       Kube setup nginx ingress -- Reload the homelab-kubernetes-provider custom fact
          setup:
            filter:   ansible_local          

      when: 
        - clusters.definition[cluster_name].ingress is defined
        - clusters.definition[cluster_name].ingress == 'nginx'
        - ansible_local['homelab-kubernetes-provider']['setup']['kube_ingress'] is not defined
