# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

- name: This playbook will configure the load balancer ingress VMs
  hosts: load_balancers

  vars_files:
    - vars/default-settings.yaml
    - group_vars/kvm_guest/cloud_images.yaml
    - group_vars/kvm_guest/load_balancer_packages.yaml
    
  tasks:

    - block:
        - name: Loading CentOS 7 cluster samples
          include_vars:
            file:        vars/testlab_samples/centos-7.yaml
            name:        c7x
        - name: Loading CentOS 8.1 cluster samples
          include_vars:
            file:        vars/testlab_samples/centos-8.1.yaml
            name:        c81
        - name: Loading CentOS 8.2 cluster samples
          include_vars:
            file:        vars/testlab_samples/centos-8.2.yaml
            name:        c82
        - name: Loading CentOS 8.3 cluster samples
          include_vars:
            file:        vars/testlab_samples/centos-8.3.yaml
            name:        c83
        - name: Loading CentOS 8 Stream cluster samples
          include_vars:
            file:        vars/testlab_samples/centos-8-stream.yaml
            name:        c8s
        - name: Loading Ubuntu 18.04 cluster samples
          include_vars:
            file:        vars/testlab_samples/ubuntu-18.04.yaml
            name:        u1804
        - name: Loading Ubuntu 20.04 cluster samples
          include_vars:
            file:        vars/testlab_samples/ubuntu-20.04.yaml
            name:        u2004
        - name: Loading Ubuntu 20.10 cluster samples
          include_vars:
            file:        vars/testlab_samples/ubuntu-20.10.yaml
            name:        u2010
        - name: Loading Your custom cluster definition
          include_vars:
            file:        vars/clusters.yaml
            name:        custo
        - name: Merging all cluster definitions
          set_fact:
            clusters: "{{ custo | combine(c7x, recursive=True) | combine(c81, recursive=True) | combine(c82, recursive=True) | combine(c83, recursive=True) | combine(c8s, recursive=True) | combine(u1804, recursive=True) | combine(u2004, recursive=True) | combine(u2010, recursive=True) }}"

    - name:  Load Balancer ingress setup -- Current provisioning facts of the VMs 
      debug:
        var: ansible_local['homelab-kubernetes-provider']

    - name:  Load balancer ingress setup -- Computing instance directory
      set_fact:
        instance_dir: "instances/{{ lookup('file', '/var/lib/dbus/machine-id') }}"
        
    - name:  Load balancer ingress setup -- Configure load balancer VMs
      block:

        - name: Load balancer ingress setup -- Set node port
          set_fact:
            ingress_http_port:  "{{ lookup ('file', instance_dir + '/' + cluster_name + '/kubelet/ingress_http_port.txt') }}"
            ingress_https_port: "{{ lookup ('file', instance_dir + '/' + cluster_name + '/kubelet/ingress_https_port.txt') }}"

        - name: Load balancer ingress setup -- Creating haproxy configuration - kubernetes ingress http
          template:
            src:               templates/haproxy/20_haproxy_kubernetes_ingress_http.cfg.j2
            dest:              /etc/haproxy/20_haproxy_kubernetes_ingress_http.cfg
          become:   true

        - name: Load balancer ingress setup -- Creating haproxy configuration - kubernetes ingress https
          template:
            src:               templates/haproxy/21_haproxy_kubernetes_ingress_https.cfg.j2
            dest:              /etc/haproxy/21_haproxy_kubernetes_ingress_https.cfg
          become:   true

        - name: Load balancer ingress setup -- Restart haproxy daemon
          command: systemctl restart haproxy
          become:          true

        - name: Load balancer ingress setup -- Storing new state inside the homelab-kubernetes-provider custom fact
          lineinfile:
            path:   /etc/ansible/facts.d/homelab-kubernetes-provider.fact
            line:   "ingress=true"
          become:   true

        - name: Load balancer ingress setup -- Reload the homelab-kubernetes-provider custom fact
          setup:
            filter: ansible_local          

      when: 
        - clusters.definition[cluster_name].control_planes.vms > 1
        - load_balancer_packages[clusters.definition[cluster_name].guest_os] is defined
        - load_balancer_packages[clusters.definition[cluster_name].guest_os].supported is defined
        - load_balancer_packages[clusters.definition[cluster_name].guest_os].supported == True
        - ansible_local['homelab-kubernetes-provider']['setup']['ingress'] is not defined
