# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

#
# We are using the last available cri-o version as defined at the official github project
#
#   https://github.com/cri-o/cri-o/blob/master/install.md#install-packaged-versions-of-cri-o
#
containerd_packages:
  "Ubuntu 20.04":
    apt_containerd_list:
      - { state: "present", name: "containerd"         		        }

  "Ubuntu 20.10":
    apt_containerd_list:
      - { state: "present", name: "containerd"         		        }

  "CentOS 7":
    repo_docker_ce_url:         "https://download.docker.com/linux/centos/docker-ce.repo"
    yum_prerequisite_list:
      - { state: "present", name: "device-mapper-persistent-data"       }  
      - { state: "present", name: "lvm2"         			}  
    yum_containerd_list:
      - { state: "present", name: "containerd.io"       		}

  "CentOS 8 Stream":
    repo_docker_ce_url:         "https://download.docker.com/linux/centos/docker-ce.repo"
    yum_prerequisite_list:
      - { state: "present", name: "device-mapper-persistent-data"       }  
      - { state: "present", name: "lvm2"         			}  
    yum_containerd_list:
      - { state: "present", name: "containerd.io"       		}

