# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

#
# We are using the last available cri-o version as defined at the official github project
#
#   https://github.com/cri-o/cri-o/blob/master/install.md#install-packaged-versions-of-cri-o
#
crio_packages:
  "Ubuntu 20.04":
    os:                         "xUbuntu_20.04"
    version:                    "1.20"
    repo_lib_container_url:     "http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/"
    repo_lib_container_key_cmd: "curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/$OS/Release.key | apt-key add -"
    repo_crio_url:              "http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/"
    repo_crio_key_cmd:          "curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key | apt-key add -"

  "Ubuntu 20.10":
    os:                         "xUbuntu_20.10"
    version:                    "1.18"
    repo_lib_container_url:     "http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/"
    repo_lib_container_key_cmd: "curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/$OS/Release.key | apt-key add -"
    repo_crio_url:              "http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/"
    repo_crio_key_cmd:          "curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key | apt-key add -"

  "CentOS 7":
    os:                         "CentOS_7"
    version:                    "1.20"
    may_detach_mounts:          True
    repo_lib_container_url:     "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/devel:kubic:libcontainers:stable.repo"
    repo_cri_versioned_url:     "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo"

  "CentOS 8 Stream":
    os:                         "CentOS_8_Stream"
    version:                    "1.19"
    repo_lib_container_url:     "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/devel:kubic:libcontainers:stable.repo"
    repo_cri_versioned_url:     "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo"
