# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

ingress:
  nginx:
    k8s_definition_url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.46.0/deploy/static/provider/baremetal/deploy.yaml

  haproxy:
    k8s_definition_url: https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.6.1/deploy/haproxy-ingress.yaml
